sonar.organization=robinlrn
sonar.projectKey=RobinLRN_cesizen_project
sonar.projectName=cesizen_project

# Code source analysé (le backend Node.js)
sonar.sources=backend/src

sonar.sourceEncoding=UTF-8
