blank_issues_enabled: false
contact_links:
  - name: ❓ Question ou demande de support
    url: https://github.com/RobinLRN/cesizen_project/discussions
    about: Pour une question générale, utilisez les Discussions plutôt qu'une issue.
